### PR TITLE
Update output blobName

### PR DESCRIPTION
**Pull request by v-jiaodi**
Update the output file name `blobName` with the uploaded image name.

@spelluru, @xirzec, @kyle-patterson, @tg-msft and @EmmaZhu for notification.

### CODE REVIEW

**Comment by spelluru** [comment]
Thanks @v-jiaodi. I will update the tutorial after this PR is merged.

**Comment by v-xuto** [comment]
@spelluru, @xirzec, @kyle-patterson, @tg-msft and @EmmaZhu Could you please review this PR?

**Comment by spelluru** [comment]
@v-xuto - Looks good to me. I don't have permissions to merge though. Thanks.

**Comment by v-xuto** [comment]
@Jongio Please help merge this PR.

**Pull request merged**
